"""Add schema column to core plugin table

Revision ID: 0863f28ba0d7
Revises: 723db7117668
Create Date: 2025-12-31 20:33:49.450012+07:00

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0863f28ba0d7'
down_revision = '723db7117668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin', sa.Column('schema', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plugin', 'schema')
    # ### end Alembic commands ###
