"""Add schema column to plugins

Revision ID: 6e852e9da76b
Revises: 723db7117668
Create Date: 2026-01-15 16:49:33.631090+07:00

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6e852e9da76b'
down_revision = '723db7117668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin', sa.Column('schema', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plugin', 'schema')
    # ### end Alembic commands ###
